//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLibrary.MainRes", typeof(MainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Category.
        /// </summary>
        public static string ArticleCategoryId {
            get {
                return ResourceManager.GetString("ArticleCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Description.
        /// </summary>
        public static string ChallengeDescription {
            get {
                return ResourceManager.GetString("ChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge PicUrl.
        /// </summary>
        public static string ChallengePicUrl {
            get {
                return ResourceManager.GetString("ChallengePicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Age.
        /// </summary>
        public static string ChildAge {
            get {
                return ResourceManager.GetString("ChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Family.
        /// </summary>
        public static string ChildFamily {
            get {
                return ResourceManager.GetString("ChildFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Gender.
        /// </summary>
        public static string ChildGender {
            get {
                return ResourceManager.GetString("ChildGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Name.
        /// </summary>
        public static string ChildName {
            get {
                return ResourceManager.GetString("ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTA Link.
        /// </summary>
        public static string CTALink {
            get {
                return ResourceManager.GetString("CTALink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTA Text.
        /// </summary>
        public static string CTAText {
            get {
                return ResourceManager.GetString("CTAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Work.
        /// </summary>
        public static string DateOfWork {
            get {
                return ResourceManager.GetString("DateOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description For Editor.
        /// </summary>
        public static string DescriptionForEditor {
            get {
                return ResourceManager.GetString("DescriptionForEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Family.
        /// </summary>
        public static string FatherFamily {
            get {
                return ResourceManager.GetString("FatherFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Phonenumber.
        /// </summary>
        public static string FatherPhonenumber {
            get {
                return ResourceManager.GetString("FatherPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Files Url.
        /// </summary>
        public static string GalleryFilesUrl {
            get {
                return ResourceManager.GetString("GalleryFilesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Pic Dark.
        /// </summary>
        public static string IconPicDark {
            get {
                return ResourceManager.GetString("IconPicDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Pic Light.
        /// </summary>
        public static string IconPicLight {
            get {
                return ResourceManager.GetString("IconPicLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active State.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Pin.
        /// </summary>
        public static string IsPin {
            get {
                return ResourceManager.GetString("IsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Content.
        /// </summary>
        public static string MenuContent {
            get {
                return ResourceManager.GetString("MenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Family.
        /// </summary>
        public static string MotherFamily {
            get {
                return ResourceManager.GetString("MotherFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Phonenumber.
        /// </summary>
        public static string MotherPhonenumber {
            get {
                return ResourceManager.GetString("MotherPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Phonenumber.
        /// </summary>
        public static string ParentPhonenumber {
            get {
                return ResourceManager.GetString("ParentPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic Url.
        /// </summary>
        public static string PicUrl {
            get {
                return ResourceManager.GetString("PicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic Url Dark.
        /// </summary>
        public static string PicUrlDark {
            get {
                return ResourceManager.GetString("PicUrlDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic Url Light.
        /// </summary>
        public static string PicUrlLight {
            get {
                return ResourceManager.GetString("PicUrlLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio Category Title.
        /// </summary>
        public static string PortfolioCategoryTitle {
            get {
                return ResourceManager.GetString("PortfolioCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Pic Url.
        /// </summary>
        public static string ProfilePicUrl {
            get {
                return ResourceManager.GetString("ProfilePicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Desc.
        /// </summary>
        public static string ShortDesc {
            get {
                return ResourceManager.GetString("ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Text.
        /// </summary>
        public static string SMSText {
            get {
                return ResourceManager.GetString("SMSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Description.
        /// </summary>
        public static string SolutionDescription {
            get {
                return ResourceManager.GetString("SolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution PicUrl.
        /// </summary>
        public static string SolutionPicUrl {
            get {
                return ResourceManager.GetString("SolutionPicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb Pic Url.
        /// </summary>
        public static string ThumbPicUrl {
            get {
                return ResourceManager.GetString("ThumbPicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
