//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLibrary.Resources.Setting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLibrary.Resources.Setting.SettingRes", typeof(SettingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Model.
        /// </summary>
        public static string AIModel {
            get {
                return ResourceManager.GetString("AIModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Pre Description.
        /// </summary>
        public static string AIPreDescription {
            get {
                return ResourceManager.GetString("AIPreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Token.
        /// </summary>
        public static string AIToken {
            get {
                return ResourceManager.GetString("AIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparat Link.
        /// </summary>
        public static string AparatLink {
            get {
                return ResourceManager.GetString("AparatLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bale Link.
        /// </summary>
        public static string BaleLink {
            get {
                return ResourceManager.GetString("BaleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eita Link.
        /// </summary>
        public static string EitaLink {
            get {
                return ResourceManager.GetString("EitaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Password.
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email SMTP Port.
        /// </summary>
        public static string EmailSMTPPort {
            get {
                return ResourceManager.GetString("EmailSMTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email SMTP Url.
        /// </summary>
        public static string EmailSMTPUrl {
            get {
                return ResourceManager.GetString("EmailSMTPUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email SSL.
        /// </summary>
        public static string EmailSSL {
            get {
                return ResourceManager.GetString("EmailSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Username.
        /// </summary>
        public static string EmailUsername {
            get {
                return ResourceManager.GetString("EmailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavIcon Url.
        /// </summary>
        public static string FavIconUrl {
            get {
                return ResourceManager.GetString("FavIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject Code in Footer.
        /// </summary>
        public static string InjectFooter {
            get {
                return ResourceManager.GetString("InjectFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject Code in Header.
        /// </summary>
        public static string InjectHeader {
            get {
                return ResourceManager.GetString("InjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Link.
        /// </summary>
        public static string InstagramLink {
            get {
                return ResourceManager.GetString("InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkein Link.
        /// </summary>
        public static string LinkeinLink {
            get {
                return ResourceManager.GetString("LinkeinLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Url.
        /// </summary>
        public static string LogoUrl {
            get {
                return ResourceManager.GetString("LogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO.
        /// </summary>
        public static string SeoList {
            get {
                return ResourceManager.GetString("SeoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting not found for this lang.
        /// </summary>
        public static string SettingNotFound {
            get {
                return ResourceManager.GetString("SettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Title.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Credit.
        /// </summary>
        public static string SMSCredit {
            get {
                return ResourceManager.GetString("SMSCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Link.
        /// </summary>
        public static string TelegramLink {
            get {
                return ResourceManager.GetString("TelegramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell.
        /// </summary>
        public static string Tell {
            get {
                return ResourceManager.GetString("Tell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Link.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        public static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
    }
}
